name: Lint

on:
  push:
    branches:
      - main

jobs:
    simple_deploiment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Install dependencies
              run: |
                npm install
            - name: Install dependencies jest sjdom
              run: |
                npm install -D jest-environment-jsdom
            - name: Check style
              run: |
                npx eslint ./src
            - name: Build
              run: |
                npm run build
            - name: Test
              run: |
                npm test