name: pipeline

on:
    push:
        branches:
            - main

jobs:
    Hello_World:
        runs-on: ubuntu 20.04
        steps:
            - name: Say Hello
              run: |
                echo "Hello World !"